messages = {
    "uz": {
        "start_lang": "🇺🇿 Tilni tanlang:\n⬇️",
        "enter_name": "🤵 Iltimos, to‘liq ismingizni kiriting (Ism Familiya):",
        "enter_nick": "🎮 Endi o‘yindagi ismingizni (nickname) kiriting:",
        "registered": "✅ Ro‘yxatdan o‘tdingiz!",
        "profile": "👤 Profil",
        "change_name": "✏️ Ismni o‘zgartirish",
        "change_lang": "🌐 Tilni o‘zgartirish",
        "your_id": "🆔 ID",
        "your_name": "👥 Ism",
        "your_nick": "🎮 Nick",
        "your_score": "🎯 Ball",
        "your_rank": "🎖 Daraja",
        "your_turnirs": "🏆 Turnirlar",
        "select_lang": "🌐 Yangi tilni tanlang:",
        "instruction_text": "ℹ️ Hozircha o‘zbekcha instruktsiya yo‘q.",
    },
    "ru": {
        "start_lang": "🇷🇺 Выберите язык:\n⬇️",
        "enter_name": "🤵 Введите ваше полное имя (Имя Фамилия):",
        "enter_nick": "🎮 Теперь введите свой игровой никнейм:",
        "registered": "✅ Вы зарегистрированы!",
        "profile": "👤 Профиль",
        "change_name": "✏️ Изменить имя",
        "change_lang": "🌐 Изменить язык",
        "your_id": "🆔 ID",
        "your_name": "👥 Имя",
        "your_nick": "🎮 Ник",
        "your_score": "🎯 Очки",
        "your_rank": "🎖 Звание",
        "your_turnirs": "🏆 Турниры",
        "select_lang": "🌐 Выберите новый язык:",
        "instruction_text": "ℹ️ Пока нет инструкции на русском языке.",
    }
}